version: '3'

volumes:
  mysql:
    driver: "local"

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www  
    env_file:
      - ./.env
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/bolt.dev.ini:/usr/local/etc/php/conf.d/local.ini
  #Nginx Service
  nginx:
    image: nginx:1.11.1-alpine
    depends_on:
      - app
      - mysql
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log/error.log:/var/log/nginx/error.log
      - ./docker/nginx/log/access.log:/var/log/nginx/access.log
  #mysql Service
  mysql:
    image: bitnami/mysql:8.0.23
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: bolt
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bilas
      MYSQL_PASSWORD: tiptop123
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
  #phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8889:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    environment:
      PMA_HOST: mysql