# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the <b>first<b> menu item.
    link: homepage
    class: homepage
  - label: Service
    title: This is the Services menu item.
    link: service
    class: homepage
  - label: About US
    title: This is the About US menu item.
    link: aboutus
    class: homepage
  - label: Contact US
    title: This is the Contact US menu item.
    link: contactus
    class: homepage
  - label: About
    link: page/2
    submenu:
        - label: Sub 1
          link: entry/39
        - label: Sub 2
          class: menu-item-class
          link: entry/40
        - link: entry/41 # These two have no `label`, so they will show up as the title
        - class: sub-class
          link: page/42
  - label: All pages
    link: pages/

foo: bar
